# Generated by Django 5.0.3 on 2024-05-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(verbose_name='Стаття')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час редагування')),
            ],
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва команди')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('emblem', models.ImageField(upload_to='media/photos/', verbose_name='Емблема команди')),
                ('town', models.CharField(max_length=50, verbose_name='Місто')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Назва країни')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('flag', models.ImageField(upload_to='media/photos/', verbose_name='Прапор країни')),
            ],
        ),
    ]
