# Generated by Django 5.0.3 on 2024-05-01 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='articles',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs',
                                    verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='country',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='clubs.countries',
                                    verbose_name='Країна'),
        ),
    ]
