# Generated by Django 5.0.3 on 2025-04-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статті', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='clubs',
            options={'verbose_name': 'Команди', 'verbose_name_plural': 'Команди'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Країни', 'verbose_name_plural': 'Країни'},
        ),
        migrations.AddField(
            model_name='articles',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.countries',
                                    verbose_name='Країна'),
        ),
    ]
