# Generated by Django 5.0.3 on 2025-05-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clubs', '0003_alter_articles_options_alter_clubs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/photos/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва статті'),
        ),
    ]
