# Generated by Django 5.0.3 on 2025-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clubs', '0004_articles_photo_alter_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
